### ISSUE TITLE
How to fix the wrong hight of clickable tag buttons?

### ISSUE THREAD

**Issue by EugeneTarasenko** [AnKing-Memberships/clickable-tags#5]
My clickable tag buttons have a wrong height. It's smaller than the text inside it. Is there any way to fix it?
<img width="151" alt="Screenshot 2023-05-09 at 23 05 51" src="https://github.com/AnKing-Memberships/clickable-tags/assets/87163666/ac345c41-6d0d-4eae-a48c-2dc33908f4a9">

**Comment by mldwn** [comment]
Hello, 
I have the same problem. Were you able to find a solution ?

**Comment by mldwn** [comment]
> Hello, I have the same problem. Were you able to find a solution ?

Thank you very much

**Comment by EugeneTarasenko** [comment]
Yes. The problem was with the "`box-sizing`" property. You shouldn't changed. It should have its initial ,"`content-box`" value.

**Comment by mldwn** [comment]
Thank you for your response. How do you make it go back to the inital value ?

**Comment by EugeneTarasenko** [comment]
In the styling section of the card template delete all the lines that have the "box-sizing" property.
for example

.card {
    ~~box-sizing: border-box;~~
}

**Comment by mldwn** [comment]
Thank you very much !!
